#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InzApp.Resource", IsApplication=true)]

namespace InzApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int ContextMenu = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addFriend = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int friendsMessages = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int myFriends = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int myMessages = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int NewMessage = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int otherTravelers = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060025
			public const int MyFriendMessagesTitleTextView = 2131099685;
			
			// aapt resource value: 0x7f06002a
			public const int MyFriendsListView = 2131099690;
			
			// aapt resource value: 0x7f06000c
			public const int OtherTravelerEndPlaceEditText = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int OtherTravelerStartPlaceEditText = 2131099659;
			
			// aapt resource value: 0x7f060035
			public const int OtherTravelersMessagesAgeTextView = 2131099701;
			
			// aapt resource value: 0x7f060032
			public const int OtherTravelersMessagesListView = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int OtherTravelersMessagesNameTextView = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int OtherTravelersMessagesSurnameTextView = 2131099700;
			
			// aapt resource value: 0x7f060030
			public const int OtherTravelersMessagesTitleTextView = 2131099696;
			
			// aapt resource value: 0x7f06002f
			public const int addButton = 2131099695;
			
			// aapt resource value: 0x7f060029
			public const int addFriendImageButton = 2131099689;
			
			// aapt resource value: 0x7f060005
			public const int addFriendListView = 2131099653;
			
			// aapt resource value: 0x7f060031
			public const int ageTextView = 2131099697;
			
			// aapt resource value: 0x7f060004
			public const int dateOfBirthTextView = 2131099652;
			
			// aapt resource value: 0x7f060013
			public const int emailField = 2131099667;
			
			// aapt resource value: 0x7f06002e
			public const int endPlaceEditText = 2131099694;
			
			// aapt resource value: 0x7f060028
			public const int endPlaceTextView = 2131099688;
			
			// aapt resource value: 0x7f060009
			public const int findFriendButton = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int findOtherTravelerButton = 2131099661;
			
			// aapt resource value: 0x7f06001b
			public const int forgottenPwButton = 2131099675;
			
			// aapt resource value: 0x7f06000f
			public const int forgottenPwEmailField = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int forgottenPwText = 2131099662;
			
			// aapt resource value: 0x7f060006
			public const int friendAddButton = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int friendNameEditText = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int friendSurnameEditText = 2131099656;
			
			// aapt resource value: 0x7f060021
			public const int friendsImageButton = 2131099681;
			
			// aapt resource value: 0x7f06001d
			public const int friendsMsgImageButton = 2131099677;
			
			// aapt resource value: 0x7f060016
			public const int linearLayout1 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int linearLayout2 = 2131099671;
			
			// aapt resource value: 0x7f06001a
			public const int linearLayout3 = 2131099674;
			
			// aapt resource value: 0x7f06001f
			public const int linearLayout4 = 2131099679;
			
			// aapt resource value: 0x7f060022
			public const int linearLayout5 = 2131099682;
			
			// aapt resource value: 0x7f060015
			public const int loginButton = 2131099669;
			
			// aapt resource value: 0x7f060012
			public const int loginText = 2131099666;
			
			// aapt resource value: 0x7f06001c
			public const int msgImageButton = 2131099676;
			
			// aapt resource value: 0x7f060011
			public const int myFriendMessagesListView = 2131099665;
			
			// aapt resource value: 0x7f06002c
			public const int myMessagesListView = 2131099692;
			
			// aapt resource value: 0x7f060002
			public const int nameTextView = 2131099650;
			
			// aapt resource value: 0x7f06002b
			public const int newMsgImageButton = 2131099691;
			
			// aapt resource value: 0x7f06000a
			public const int otherTravelerTimeTextView = 2131099658;
			
			// aapt resource value: 0x7f060014
			public const int passField = 2131099668;
			
			// aapt resource value: 0x7f06003c
			public const int regButton = 2131099708;
			
			// aapt resource value: 0x7f06003b
			public const int regDoBTextView = 2131099707;
			
			// aapt resource value: 0x7f060036
			public const int regEMailEditText = 2131099702;
			
			// aapt resource value: 0x7f060039
			public const int regNameEditText = 2131099705;
			
			// aapt resource value: 0x7f060038
			public const int regPwConfirmEditText = 2131099704;
			
			// aapt resource value: 0x7f060037
			public const int regPwEditText = 2131099703;
			
			// aapt resource value: 0x7f06003a
			public const int regSurnameEditText = 2131099706;
			
			// aapt resource value: 0x7f060019
			public const int registerButton = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int registerText = 2131099672;
			
			// aapt resource value: 0x7f060010
			public const int remindButton = 2131099664;
			
			// aapt resource value: 0x7f060001
			public const int rowLinearLayout = 2131099649;
			
			// aapt resource value: 0x7f06002d
			public const int startPlaceEditText = 2131099693;
			
			// aapt resource value: 0x7f060027
			public const int startPlaceTextView = 2131099687;
			
			// aapt resource value: 0x7f060003
			public const int surnameTextView = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f06001e
			public const int textView2 = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int textView3 = 2131099680;
			
			// aapt resource value: 0x7f060024
			public const int textView4 = 2131099684;
			
			// aapt resource value: 0x7f060026
			public const int timeTextView = 2131099686;
			
			// aapt resource value: 0x7f060023
			public const int travelersImageButton = 2131099683;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddFriend = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddFriendListViewRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FindFriendToAdd = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FindOtherTravelers = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ForgottenPw = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int FriendsMessages = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Login = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MyFriendMessages = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MyFriends = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int MyFriendsListViewRow = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int MyMessageListViewRow = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int MyMessages = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int NewMessage = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int OtherTravelers = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int OtherTravelersListViewRow = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Register = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000a
			public const int AddFriendLabel = 2130968586;
			
			// aapt resource value: 0x7f040000
			public const int ApiLink = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f04000f
			public const int ContextMenuTitle = 2130968591;
			
			// aapt resource value: 0x7f040009
			public const int FindFriendToAddLabel = 2130968585;
			
			// aapt resource value: 0x7f040027
			public const int FindFriendToAddNoDataInfo = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int FindFriendToAddNotFoundInfo = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int FindFriendToAddNotOkInfo = 2130968617;
			
			// aapt resource value: 0x7f04000b
			public const int FindOtherTravelers = 2130968587;
			
			// aapt resource value: 0x7f04003a
			public const int ForgottenPwEmailNotCorrectInfo = 2130968634;
			
			// aapt resource value: 0x7f04000e
			public const int ForgottenPwLabel = 2130968590;
			
			// aapt resource value: 0x7f04003c
			public const int ForgottenPwRequestCanceledInfo = 2130968636;
			
			// aapt resource value: 0x7f04003b
			public const int ForgottenPwRequestNotOkInfo = 2130968635;
			
			// aapt resource value: 0x7f040039
			public const int ForgottenPwRequestOkInfo = 2130968633;
			
			// aapt resource value: 0x7f04002c
			public const int FoundFriendAmbiguous = 2130968620;
			
			// aapt resource value: 0x7f04002b
			public const int FoundFriendNotSelectedInfo = 2130968619;
			
			// aapt resource value: 0x7f04002a
			public const int FoundFriendSelectedInfo = 2130968618;
			
			// aapt resource value: 0x7f040026
			public const int FriendAddCanceledInfo = 2130968614;
			
			// aapt resource value: 0x7f040025
			public const int FriendAddNotOkInfo = 2130968613;
			
			// aapt resource value: 0x7f040024
			public const int FriendAddOkInfo = 2130968612;
			
			// aapt resource value: 0x7f040023
			public const int FriendDeleteNotOkInfo = 2130968611;
			
			// aapt resource value: 0x7f040022
			public const int FriendDeleteOkInfo = 2130968610;
			
			// aapt resource value: 0x7f040007
			public const int FriendMessagesLabel = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int FriendsMessagesLabel = 2130968582;
			
			// aapt resource value: 0x7f04001f
			public const int LoadingFriendListContent = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int LoadingFriendListEmptyInfo = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int LoadingFriendListNotOkInfo = 2130968609;
			
			// aapt resource value: 0x7f04001e
			public const int LoadingFriendListTitle = 2130968606;
			
			// aapt resource value: 0x7f04001a
			public const int LoadingFriendMessageNotFoundInfo = 2130968602;
			
			// aapt resource value: 0x7f040017
			public const int LoadingMessageContent = 2130968599;
			
			// aapt resource value: 0x7f040019
			public const int LoadingMessageNotFoundInfo = 2130968601;
			
			// aapt resource value: 0x7f040018
			public const int LoadingMessageNotOkInfo = 2130968600;
			
			// aapt resource value: 0x7f040016
			public const int LoadingMessageTitle = 2130968598;
			
			// aapt resource value: 0x7f040048
			public const int LoginFieldsNoDataInfo = 2130968648;
			
			// aapt resource value: 0x7f040046
			public const int LoginProgressContent = 2130968646;
			
			// aapt resource value: 0x7f040045
			public const int LoginProgressTitle = 2130968645;
			
			// aapt resource value: 0x7f040047
			public const int LoginTokenOrTravelerFailure = 2130968647;
			
			// aapt resource value: 0x7f04004a
			public const int LogoutConfirmationContent = 2130968650;
			
			// aapt resource value: 0x7f04004d
			public const int LogoutConfirmationLoggedOutMessage = 2130968653;
			
			// aapt resource value: 0x7f04004e
			public const int LogoutConfirmationLogoutCancelled = 2130968654;
			
			// aapt resource value: 0x7f04004c
			public const int LogoutConfirmationNegativeButtonText = 2130968652;
			
			// aapt resource value: 0x7f04004b
			public const int LogoutConfirmationPositiveButtonText = 2130968651;
			
			// aapt resource value: 0x7f040049
			public const int LogoutConfirmationTitle = 2130968649;
			
			// aapt resource value: 0x7f040004
			public const int MainLabel = 2130968580;
			
			// aapt resource value: 0x7f040014
			public const int MessageDeleteNotOkInfo = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int MessageDeleteOkInfo = 2130968595;
			
			// aapt resource value: 0x7f04001b
			public const int MyFriendMessagesTitle = 2130968603;
			
			// aapt resource value: 0x7f040008
			public const int MyFriendsLabel = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int MyMessagesLabel = 2130968581;
			
			// aapt resource value: 0x7f040012
			public const int NewMessageAddCanceledInfo = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int NewMessageAddNotOkInfo = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int NewMessageAddOkInfo = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int NewMessageLabel = 2130968589;
			
			// aapt resource value: 0x7f040015
			public const int NewMessageNoDataInfo = 2130968597;
			
			// aapt resource value: 0x7f04004f
			public const int NoConnectionInfo = 2130968655;
			
			// aapt resource value: 0x7f04000c
			public const int OtherTravelersLabel = 2130968588;
			
			// aapt resource value: 0x7f040040
			public const int OtherTravelersListLoadingContent = 2130968640;
			
			// aapt resource value: 0x7f04003f
			public const int OtherTravelersListLoadingTitle = 2130968639;
			
			// aapt resource value: 0x7f040044
			public const int OtherTravelersListTitle = 2130968644;
			
			// aapt resource value: 0x7f040041
			public const int OtherTravelersNoDataInfo = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int OtherTravelersNotFoundInfo = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int OtherTravelersNotOkInfo = 2130968643;
			
			// aapt resource value: 0x7f040003
			public const int RegisterLabel = 2130968579;
			
			// aapt resource value: 0x7f040031
			public const int RegisterUserCanceledInfo = 2130968625;
			
			// aapt resource value: 0x7f040034
			public const int RegisterUserEmailNotCorrectInfo = 2130968628;
			
			// aapt resource value: 0x7f040032
			public const int RegisterUserModelNotOkInfo = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int RegisterUserNoDataInfo = 2130968627;
			
			// aapt resource value: 0x7f040030
			public const int RegisterUserNotOkInfo = 2130968624;
			
			// aapt resource value: 0x7f04002f
			public const int RegisterUserOkInfo = 2130968623;
			
			// aapt resource value: 0x7f040036
			public const int RegisterUserPwNotMatchingPolicyInfo = 2130968630;
			
			// aapt resource value: 0x7f040035
			public const int RegisterUserPwsNotEqualInfo = 2130968629;
			
			// aapt resource value: 0x7f04002e
			public const int SearchingForFriendContent = 2130968622;
			
			// aapt resource value: 0x7f04002d
			public const int SearchingForFriendTitle = 2130968621;
			
			// aapt resource value: 0x7f040001
			public const int SecureApiLink = 2130968577;
			
			// aapt resource value: 0x7f04003e
			public const int SendingForgottenPwRequestContent = 2130968638;
			
			// aapt resource value: 0x7f04003d
			public const int SendingForgottenPwRequestTitle = 2130968637;
			
			// aapt resource value: 0x7f04001d
			public const int SendingMessageContent = 2130968605;
			
			// aapt resource value: 0x7f04001c
			public const int SendingMessageTitle = 2130968604;
			
			// aapt resource value: 0x7f040038
			public const int SendingUserRegisterContent = 2130968632;
			
			// aapt resource value: 0x7f040037
			public const int SendingUserRegisterTitle = 2130968631;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
